name: BQ-NPCs-Addon
version: '${project.version}'
main: ree.theos.bqnpcsaddon.BQ_NPCs_Addon
api-version: '1.18'
depend: [BetonQuest]
authors: [TheosRee]
description: Adds several NPC plugins to BetonQuest
